# Generated by Django 3.2 on 2022-02-25 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('mobile', models.CharField(max_length=255)),
                ('address', models.TextField(default='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receipt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customers',
                'ordering': ('-date_created',),
            },
        ),
        migrations.RemoveField(
            model_name='receipthistory',
            name='email',
        ),
        migrations.RemoveField(
            model_name='receipthistory',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='receipthistory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='receipthistory',
            name='total_amount_payable',
        ),
        migrations.RemoveField(
            model_name='receipthistory',
            name='user',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_obj', to='core.customer')),
            ],
            options={
                'db_table': 'order',
                'ordering': ('-date_created',),
            },
        ),
        migrations.AddField(
            model_name='receipthistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_receipt', to='core.orders'),
        ),
    ]
